#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
ifeq ($(strip $(DEVKITARM)),)
$(error "Please set DEVKITARM in your environment. export DEVKITARM=<path to>devkitARM")
endif

export TARGET	:=	wasm4-aot-nds
export TOPDIR	:=	$(CURDIR)

# specify a directory which contains the nitro filesystem
# this is relative to the Makefile
NITRO_FILES	:=

# These set the information text in the nds file
#GAME_TITLE     := My Wonderful Homebrew
#GAME_SUBTITLE1 := built with devkitARM
#GAME_SUBTITLE2 := http://devitpro.org

include $(DEVKITARM)/ds_rules

.PHONY: checkarm7 checkarm9 clean

#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
all: checkarm7 checkarm9 $(TARGET).nds

#---------------------------------------------------------------------------------
checkarm7:
	$(MAKE) -f Makefile.dkp-nds.arm7

#---------------------------------------------------------------------------------
checkarm9:
	$(MAKE) -f Makefile.dkp-nds.arm9

#---------------------------------------------------------------------------------
$(TARGET).nds	: $(NITRO_FILES) build-dkp-nds-arm7/$(TARGET).elf build-dkp-nds-arm9/$(TARGET).elf
	ndstool	-c $(TARGET).nds -7 build-dkp-nds-arm7/$(TARGET).elf -9 build-dkp-nds-arm9/$(TARGET).elf \
	-b $(GAME_ICON) "$(GAME_TITLE);$(GAME_SUBTITLE1);$(GAME_SUBTITLE2)" \
	$(_ADDFILES)

#---------------------------------------------------------------------------------
build-dkp-nds-arm7/$(TARGET).elf:
	$(MAKE) -f Makefile.dkp-nds.arm7

#---------------------------------------------------------------------------------
build-dkp-nds-arm9/$(TARGET).elf:
	$(MAKE) -f Makefile.dkp-nds.arm9

#---------------------------------------------------------------------------------
clean:
	$(MAKE) -f Makefile.dkp-nds.arm9 clean
	$(MAKE) -f Makefile.dkp-nds.arm7 clean
	rm -f $(TARGET).nds
